/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasAreaRouteImport } from './routes/areas.$area'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTheoryRouteImport } from './routes/_authenticated/theory'
import { Route as AuthenticatedSignsRouteImport } from './routes/_authenticated/signs'
import { Route as AuthenticatedRoadSignsRouteImport } from './routes/_authenticated/road-signs'
import { Route as AuthenticatedQuestionsRouteImport } from './routes/_authenticated/questions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMockTestsRouteImport } from './routes/_authenticated/mock-tests'
import { Route as AuthenticatedLessonsRouteImport } from './routes/_authenticated/lessons'
import { Route as AuthenticatedHighwayCodeRouteImport } from './routes/_authenticated/highway-code'
import { Route as AuthenticatedHazardPerceptionRouteImport } from './routes/_authenticated/hazard-perception'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPwaInstallsRouteImport } from './routes/_authenticated/admin.pwa-installs'
import { Route as AuthenticatedAdminHazardVideosRouteImport } from './routes/_authenticated/admin.hazard-videos'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin.diagnostics'
import { Route as AuthenticatedAdminContactClicksRouteImport } from './routes/_authenticated/admin.contact-clicks'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin.access'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaRoute = AreasAreaRouteImport.update({
  id: '/areas/$area',
  path: '/areas/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTheoryRoute = AuthenticatedTheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignsRoute = AuthenticatedSignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadSignsRoute = AuthenticatedRoadSignsRouteImport.update({
  id: '/road-signs',
  path: '/road-signs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestionsRoute = AuthenticatedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMockTestsRoute = AuthenticatedMockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonsRoute = AuthenticatedLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHighwayCodeRoute =
  AuthenticatedHighwayCodeRouteImport.update({
    id: '/highway-code',
    path: '/highway-code',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHazardPerceptionRoute =
  AuthenticatedHazardPerceptionRouteImport.update({
    id: '/hazard-perception',
    path: '/hazard-perception',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPwaInstallsRoute =
  AuthenticatedAdminPwaInstallsRouteImport.update({
    id: '/pwa-installs',
    path: '/pwa-installs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHazardVideosRoute =
  AuthenticatedAdminHazardVideosRouteImport.update({
    id: '/hazard-videos',
    path: '/hazard-videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactClicksRoute =
  AuthenticatedAdminContactClicksRouteImport.update({
    id: '/contact-clicks',
    path: '/contact-clicks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hazard-perception': typeof AuthenticatedHazardPerceptionRoute
  '/highway-code': typeof AuthenticatedHighwayCodeRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/road-signs': typeof AuthenticatedRoadSignsRoute
  '/signs': typeof AuthenticatedSignsRoute
  '/theory': typeof AuthenticatedTheoryRoute
  '/api/chat': typeof ApiChatRoute
  '/areas/$area': typeof AreasAreaRoute
  '/areas/': typeof AreasIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/contact-clicks': typeof AuthenticatedAdminContactClicksRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/hazard-videos': typeof AuthenticatedAdminHazardVideosRoute
  '/admin/pwa-installs': typeof AuthenticatedAdminPwaInstallsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hazard-perception': typeof AuthenticatedHazardPerceptionRoute
  '/highway-code': typeof AuthenticatedHighwayCodeRoute
  '/lessons': typeof AuthenticatedLessonsRoute
  '/mock-tests': typeof AuthenticatedMockTestsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/questions': typeof AuthenticatedQuestionsRoute
  '/road-signs': typeof AuthenticatedRoadSignsRoute
  '/signs': typeof AuthenticatedSignsRoute
  '/theory': typeof AuthenticatedTheoryRoute
  '/api/chat': typeof ApiChatRoute
  '/areas/$area': typeof AreasAreaRoute
  '/areas': typeof AreasIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/contact-clicks': typeof AuthenticatedAdminContactClicksRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/hazard-videos': typeof AuthenticatedAdminHazardVideosRoute
  '/admin/pwa-installs': typeof AuthenticatedAdminPwaInstallsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hazard-perception': typeof AuthenticatedHazardPerceptionRoute
  '/_authenticated/highway-code': typeof AuthenticatedHighwayCodeRoute
  '/_authenticated/lessons': typeof AuthenticatedLessonsRoute
  '/_authenticated/mock-tests': typeof AuthenticatedMockTestsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/questions': typeof AuthenticatedQuestionsRoute
  '/_authenticated/road-signs': typeof AuthenticatedRoadSignsRoute
  '/_authenticated/signs': typeof AuthenticatedSignsRoute
  '/_authenticated/theory': typeof AuthenticatedTheoryRoute
  '/api/chat': typeof ApiChatRoute
  '/areas/$area': typeof AreasAreaRoute
  '/areas/': typeof AreasIndexRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/contact-clicks': typeof AuthenticatedAdminContactClicksRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/hazard-videos': typeof AuthenticatedAdminHazardVideosRoute
  '/_authenticated/admin/pwa-installs': typeof AuthenticatedAdminPwaInstallsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/instructors'
    | '/pricing'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/hazard-perception'
    | '/highway-code'
    | '/lessons'
    | '/mock-tests'
    | '/payments'
    | '/profile'
    | '/questions'
    | '/road-signs'
    | '/signs'
    | '/theory'
    | '/api/chat'
    | '/areas/$area'
    | '/areas/'
    | '/admin/access'
    | '/admin/admins'
    | '/admin/contact-clicks'
    | '/admin/diagnostics'
    | '/admin/email'
    | '/admin/hazard-videos'
    | '/admin/pwa-installs'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/instructors'
    | '/pricing'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard'
    | '/hazard-perception'
    | '/highway-code'
    | '/lessons'
    | '/mock-tests'
    | '/payments'
    | '/profile'
    | '/questions'
    | '/road-signs'
    | '/signs'
    | '/theory'
    | '/api/chat'
    | '/areas/$area'
    | '/areas'
    | '/admin/access'
    | '/admin/admins'
    | '/admin/contact-clicks'
    | '/admin/diagnostics'
    | '/admin/email'
    | '/admin/hazard-videos'
    | '/admin/pwa-installs'
    | '/admin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/instructors'
    | '/pricing'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/hazard-perception'
    | '/_authenticated/highway-code'
    | '/_authenticated/lessons'
    | '/_authenticated/mock-tests'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/questions'
    | '/_authenticated/road-signs'
    | '/_authenticated/signs'
    | '/_authenticated/theory'
    | '/api/chat'
    | '/areas/$area'
    | '/areas/'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/contact-clicks'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/hazard-videos'
    | '/_authenticated/admin/pwa-installs'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  InstructorsRoute: typeof InstructorsRoute
  PricingRoute: typeof PricingRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  AreasAreaRoute: typeof AreasAreaRoute
  AreasIndexRoute: typeof AreasIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$area': {
      id: '/areas/$area'
      path: '/areas/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof AreasAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/theory': {
      id: '/_authenticated/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof AuthenticatedTheoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signs': {
      id: '/_authenticated/signs'
      path: '/signs'
      fullPath: '/signs'
      preLoaderRoute: typeof AuthenticatedSignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/road-signs': {
      id: '/_authenticated/road-signs'
      path: '/road-signs'
      fullPath: '/road-signs'
      preLoaderRoute: typeof AuthenticatedRoadSignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions': {
      id: '/_authenticated/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mock-tests': {
      id: '/_authenticated/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof AuthenticatedMockTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons': {
      id: '/_authenticated/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/highway-code': {
      id: '/_authenticated/highway-code'
      path: '/highway-code'
      fullPath: '/highway-code'
      preLoaderRoute: typeof AuthenticatedHighwayCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hazard-perception': {
      id: '/_authenticated/hazard-perception'
      path: '/hazard-perception'
      fullPath: '/hazard-perception'
      preLoaderRoute: typeof AuthenticatedHazardPerceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pwa-installs': {
      id: '/_authenticated/admin/pwa-installs'
      path: '/pwa-installs'
      fullPath: '/admin/pwa-installs'
      preLoaderRoute: typeof AuthenticatedAdminPwaInstallsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hazard-videos': {
      id: '/_authenticated/admin/hazard-videos'
      path: '/hazard-videos'
      fullPath: '/admin/hazard-videos'
      preLoaderRoute: typeof AuthenticatedAdminHazardVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact-clicks': {
      id: '/_authenticated/admin/contact-clicks'
      path: '/contact-clicks'
      fullPath: '/admin/contact-clicks'
      preLoaderRoute: typeof AuthenticatedAdminContactClicksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminContactClicksRoute: typeof AuthenticatedAdminContactClicksRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminHazardVideosRoute: typeof AuthenticatedAdminHazardVideosRoute
  AuthenticatedAdminPwaInstallsRoute: typeof AuthenticatedAdminPwaInstallsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminContactClicksRoute: AuthenticatedAdminContactClicksRoute,
  AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminHazardVideosRoute: AuthenticatedAdminHazardVideosRoute,
  AuthenticatedAdminPwaInstallsRoute: AuthenticatedAdminPwaInstallsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHazardPerceptionRoute: typeof AuthenticatedHazardPerceptionRoute
  AuthenticatedHighwayCodeRoute: typeof AuthenticatedHighwayCodeRoute
  AuthenticatedLessonsRoute: typeof AuthenticatedLessonsRoute
  AuthenticatedMockTestsRoute: typeof AuthenticatedMockTestsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestionsRoute: typeof AuthenticatedQuestionsRoute
  AuthenticatedRoadSignsRoute: typeof AuthenticatedRoadSignsRoute
  AuthenticatedSignsRoute: typeof AuthenticatedSignsRoute
  AuthenticatedTheoryRoute: typeof AuthenticatedTheoryRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHazardPerceptionRoute: AuthenticatedHazardPerceptionRoute,
  AuthenticatedHighwayCodeRoute: AuthenticatedHighwayCodeRoute,
  AuthenticatedLessonsRoute: AuthenticatedLessonsRoute,
  AuthenticatedMockTestsRoute: AuthenticatedMockTestsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestionsRoute: AuthenticatedQuestionsRoute,
  AuthenticatedRoadSignsRoute: AuthenticatedRoadSignsRoute,
  AuthenticatedSignsRoute: AuthenticatedSignsRoute,
  AuthenticatedTheoryRoute: AuthenticatedTheoryRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  InstructorsRoute: InstructorsRoute,
  PricingRoute: PricingRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  AreasAreaRoute: AreasAreaRoute,
  AreasIndexRoute: AreasIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
